export const reporteEncabezado = [
  {
    key: "firstName",
    label: "Nombre",
  },
  {
    key: "lastName",
    label: "Apellido",
  },
  {
    key: "gender",
    label: "Género",
  },
  {
    key: "department",
    label: "Departamento",
  },
  {
    key: "totalHours",
    label: "Total de Horas",
  },
  {
    key: "accumulatedSalary",
    label: "Sueldo Acumulado ($)",
  },
  {
    key: "city",
    label: "Ciudad",
  },
];

export const reporteData = [
  {
    id: 1,
    firstName: "Juan",
    lastName: "Pérez",
    department: "Ventas",
    totalHours: 40,
    accumulatedSalary: 1000,
    gender: "Masculino",
    city: "Quito",
  },
  {
    id: 2,
    firstName: "María",
    lastName: "González",
    department: "Marketing",
    totalHours: 38,
    accumulatedSalary: 1200,
    gender: "Femenino",
    city: "Guayaquil",
  },
  {
    id: 3,
    firstName: "Carlos",
    lastName: "Rodríguez",
    department: "IT",
    totalHours: 42,
    accumulatedSalary: 1500,
    gender: "Masculino",
    city: "Cuenca",
  },
  {
    id: 4,
    firstName: "Ana",
    lastName: "López",
    department: "Recursos Humanos",
    totalHours: 36,
    accumulatedSalary: 1100,
    gender: "Femenino",
    city: "Manta",
  },
  {
    id: 5,
    firstName: "Luis",
    lastName: "Martínez",
    department: "Finanzas",
    totalHours: 40,
    accumulatedSalary: 1300,
    gender: "Masculino",
    city: "Ambato",
  },
  {
    id: 6,
    firstName: "Sofía",
    lastName: "García",
    department: "Ventas",
    totalHours: 38,
    accumulatedSalary: 1000,
    gender: "Femenino",
    city: "Loja",
  },
  {
    id: 7,
    firstName: "Diego",
    lastName: "Hernández",
    department: "Marketing",
    totalHours: 42,
    accumulatedSalary: 1200,
    gender: "Masculino",
    city: "Riobamba",
  },
  {
    id: 8,
    firstName: "Laura",
    lastName: "Torres",
    department: "IT",
    totalHours: 36,
    accumulatedSalary: 1500,
    gender: "Femenino",
    city: "Machala",
  },
  {
    id: 9,
    firstName: "José",
    lastName: "Ramírez",
    department: "Recursos Humanos",
    totalHours: 40,
    accumulatedSalary: 1100,
    gender: "Masculino",
    city: "Portoviejo",
  },
  {
    id: 10,
    firstName: "Isabel",
    lastName: "Morales",
    department: "Finanzas",
    totalHours: 38,
    accumulatedSalary: 1300,
    gender: "Femenino",
    city: "Esmeraldas",
  },
];

export const formatoReporte = [
  {
    label: "Semanal",
    value: 1,
  },
  {
    label: "Mensual",
    value: 2,
  },
  {
    label: "Anual",
    value: 3,
  },
];
